package dcit50_lab2_scoreanalyzer_molina;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nostrad
 */
public class ScoreAnalyzerForm extends javax.swing.JFrame {
    double[] scores = new double[4];
        double[][] classScores = {
        {85, 90, 88, 92},
        {78, 84, 88, 86},
        {93, 95, 89, 94},
    };
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScoreAnalyzerForm.class.getName());
    
    /**
     * Creates new form GUI
     */
    public ScoreAnalyzerForm() {
        initComponents();
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlabelStudentScoreAnalyzer = new javax.swing.JLabel();
        jlabelDescription = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        studentnameLabel = new javax.swing.JLabel();
        labelJava = new javax.swing.JLabel();
        txtJava = new javax.swing.JTextField();
        txtDatabase = new javax.swing.JTextField();
        labelDatabasescore = new javax.swing.JLabel();
        txtNetworking = new javax.swing.JTextField();
        labelNetworkingscore = new javax.swing.JLabel();
        labelMathscore = new javax.swing.JLabel();
        txtMath = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblAverage = new javax.swing.JLabel();
        lblHighest = new javax.swing.JLabel();
        lblLowest = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        lblStudent = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setName("backGround"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(73, 59, 59));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(47, 11, 47)));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlabelStudentScoreAnalyzer.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlabelStudentScoreAnalyzer.setForeground(new java.awt.Color(229, 141, 141));
        jlabelStudentScoreAnalyzer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelStudentScoreAnalyzer.setText("Student Score Analyzer");

        jlabelDescription.setBackground(new java.awt.Color(158, 220, 189));
        jlabelDescription.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        jlabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jlabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelDescription.setText("Calculate Effortlessly!");
        jlabelDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabelStudentScoreAnalyzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlabelStudentScoreAnalyzer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelDescription)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Enter Student Full Name");
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtName.addActionListener(this::txtNameActionPerformed);

        studentnameLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        studentnameLabel.setForeground(new java.awt.Color(204, 204, 255));
        studentnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentnameLabel.setText("Student Name");

        labelJava.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelJava.setForeground(new java.awt.Color(204, 204, 255));
        labelJava.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJava.setText("Java (0 - 100)");

        txtJava.setBackground(new java.awt.Color(51, 51, 51));
        txtJava.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        txtJava.setForeground(new java.awt.Color(153, 153, 153));
        txtJava.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJava.setText("0");
        txtJava.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtJava.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtJava.addActionListener(this::txtJavaActionPerformed);

        txtDatabase.setBackground(new java.awt.Color(51, 51, 51));
        txtDatabase.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        txtDatabase.setForeground(new java.awt.Color(153, 153, 153));
        txtDatabase.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDatabase.setText("0");
        txtDatabase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtDatabase.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDatabase.addActionListener(this::txtDatabaseActionPerformed);

        labelDatabasescore.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelDatabasescore.setForeground(new java.awt.Color(204, 204, 255));
        labelDatabasescore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDatabasescore.setText("Database (0 - 100)");

        txtNetworking.setBackground(new java.awt.Color(51, 51, 51));
        txtNetworking.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        txtNetworking.setForeground(new java.awt.Color(153, 153, 153));
        txtNetworking.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNetworking.setText("0");
        txtNetworking.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtNetworking.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNetworking.addActionListener(this::txtNetworkingActionPerformed);

        labelNetworkingscore.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelNetworkingscore.setForeground(new java.awt.Color(204, 204, 255));
        labelNetworkingscore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNetworkingscore.setText("Networking (0 - 100)");

        labelMathscore.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelMathscore.setForeground(new java.awt.Color(204, 204, 255));
        labelMathscore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMathscore.setText("Math (0 - 100)");

        txtMath.setBackground(new java.awt.Color(51, 51, 51));
        txtMath.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        txtMath.setForeground(new java.awt.Color(153, 153, 153));
        txtMath.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMath.setText("0");
        txtMath.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));
        txtMath.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMath.addActionListener(this::txtMathActionPerformed);

        jPanel4.setBackground(new java.awt.Color(82, 71, 71));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 15));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Total Score:");

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Average:");

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Highest Score:");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Lowest Score:");

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("R e s u l t :");

        lblTotal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0");

        lblAverage.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblAverage.setForeground(new java.awt.Color(255, 153, 51));
        lblAverage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAverage.setText("0");

        lblHighest.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblHighest.setForeground(new java.awt.Color(204, 0, 102));
        lblHighest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHighest.setText("0");

        lblLowest.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblLowest.setForeground(new java.awt.Color(255, 102, 0));
        lblLowest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLowest.setText("0");

        lblResult.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(153, 255, 153));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResult.setText("---");

        label1.setText("__________________________________________________________________________");

        lblStudent.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lblStudent.setForeground(new java.awt.Color(255, 255, 255));
        lblStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudent.setText("---");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAverage))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHighest))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLowest))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResult)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotal))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAverage))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblHighest))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblLowest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblResult))
                .addGap(16, 16, 16))
        );

        label1.getAccessibleContext().setAccessibleName("____________________");

        btnCalculate.setBackground(new java.awt.Color(0, 0, 0));
        btnCalculate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("C A L C U L A T E");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("C L E A R");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelJava, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDatabasescore))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNetworking, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelNetworkingscore, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelMathscore, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJava)
                    .addComponent(labelDatabasescore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNetworkingscore)
                    .addComponent(labelMathscore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetworking, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMath, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJavaActionPerformed

    private void txtDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatabaseActionPerformed

    private void txtNetworkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetworkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetworkingActionPerformed

    private void txtMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMathActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        String name =txtName.getText();
        lblStudent.setText(name);
        
        double javaScore =
                Double.parseDouble(txtJava.getText());
        
        double databaseScore =
                Double.parseDouble(txtDatabase.getText());
        
        double networkingScore =
                Double.parseDouble(txtNetworking.getText());
        
        double mathScore =
                Double.parseDouble(txtMath.getText());
        
        scores[0] = javaScore;
        scores[1] = databaseScore;
        scores[2] = networkingScore;
        scores[3] = mathScore;
        
        double total = calculateTotal(scores);
        double average = calculateAverage(scores);
        double highest = findHighest(scores);
        double lowest = findLowest(scores);
        
        lblTotal.setText(String.valueOf(total));
        lblAverage.setText(String.format("%.2f", average));
        lblHighest.setText(String.valueOf(highest));
        lblLowest.setText(String.valueOf(lowest));
        
        if (average >= 75){
            lblResult.setText("Passed");
        } 
        else {
            lblResult.setText("Failed");        
        }
    }//GEN-LAST:event_btnCalculateActionPerformed
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtJava.setText("");
        txtDatabase.setText("");
        txtNetworking.setText("");
        txtMath.setText("");
        
        lblTotal.setText("0");
        lblAverage.setText("0");
        lblHighest.setText("0");
        lblLowest.setText("0");
        lblResult.setText("---");
    }//GEN-LAST:event_btnClearActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScoreAnalyzerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabelDescription;
    private javax.swing.JLabel jlabelStudentScoreAnalyzer;
    private java.awt.Label label1;
    private javax.swing.JLabel labelDatabasescore;
    private javax.swing.JLabel labelJava;
    private javax.swing.JLabel labelMathscore;
    private javax.swing.JLabel labelNetworkingscore;
    private javax.swing.JLabel lblAverage;
    private javax.swing.JLabel lblHighest;
    private javax.swing.JLabel lblLowest;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel studentnameLabel;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNetworking;
    // End of variables declaration//GEN-END:variables

   public double calculateTotal(double[] scores){
    
       double total = 0;
        
    for (int i = 0; i < scores.length; i++){
        total += scores[i];
    }
    return total;
    }
    
    
    
    public double calculateAverage(double[] scores) {
        
       double total = calculateTotal(scores);
       
       double average = total / scores.length;
       
       return average;
    }
    
    public double findHighest(double[] scores){
        double highest = scores[0];
        
        for (int i = 1; i < scores.length; i++){
            if (scores[i] > highest){
                highest = scores[i];
            }
        }
        return highest;
    }
    
        public double findLowest(double[] scores){
        double lowest = scores[0];
        
        for (int i = 1; i < scores.length; i++){
            if (scores[i] < lowest){
                lowest = scores[i];
            }
        }
        return lowest;
    }
        
        public double calculateAverage(
            double score1,
            double score2,
            double score3,
            double score4)
        {return (score1 + score2 + score3 + score4) /4;
        }
        

        
}
